# This is a esp idf workflow to build ESP32 based project
name: IDF build

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  variants:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls build_configs/* | jq -R -s -c 'split("\n")[:-1]')"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: variants
    strategy:
      # The build matrix defines the different configurations to run the job with
      matrix:
        config: ${{ fromJson(needs.variants.outputs.matrix) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Replace SDKCONFIG
        run: |
          echo "Replacing SDKCONFIG"
          rm -f sdkconfig.defaults
          cp ${{ matrix.config }} sdkconfig
          echo "SDKCONFIG replaced"

      - name: idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32s3
