# This is a esp idf workflow to build ESP32 based project
name: IDF build

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  variants:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(cd build_configs && ls * | jq -R -s -c 'split("\n")[:-1]')"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: variants
    strategy:
      # The build matrix defines the different configurations to run the job with
      matrix:
        config: ${{ fromJson(needs.variants.outputs.matrix) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Replace SDKCONFIG
        run: |
          echo "Replacing SDKCONFIG"
          rm -f sdkconfig.defaults
          cp build_configs/${{ matrix.config }} sdkconfig
          echo "SDKCONFIG replaced"

      - name: Set BUILD_VERSION for tagged push
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Setting BUILD_VERSION from tag"
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BUILD_VERSION=${TAG_NAME#v}
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
          echo "BUILD_VERSION set to ${BUILD_VERSION}"
          BUILD_VARIANT=${{ matrix.config }}

      - name: idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          target: esp32s3
          command: |
            # Install protoc-c dependencies
            apt update -y
            apt install -y protobuf-compiler autotools-dev autoconf libtool-bin pkg-config libprotoc-dev
            # Install protoc-c
            git clone https://github.com/protobuf-c/protobuf-c
            cd protobuf-c
            ./autogen.sh && ./configure && make && make install
            cd ..

            #build
            idf.py build
